name: Esegui Bot i Killer

on:
  schedule:
    - cron: '0 * * * *' # Gira ogni ora spaccata
  workflow_dispatch: # Permette di avviarlo a mano con un tasto

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Scarica il codice
        uses: actions/checkout@v3
      
      - name: Installa Python
        uses: actions/setup-python@v4
        with:
          python-main: '3.9'
          
      - name: Installa pacchetti
        run: pip install -r requirements.txt
        
      - name: Avvia il Bot
        env:
          TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_TOKEN }}
          TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
        run: python main.py
